package consts

const (
	CtxKeyUserid                          string = "user_id"
	BearerTokenPrefix                     string = "Bearer "
	HeaderTypeAuthorization               string = "Authorization"
	RouteUrlBase                          string = "/api"
	RouteUrlLogin                         string = RouteUrlBase + "/login"
	RouteUrlUserData                      string = RouteUrlBase + "/user/get"
	RouteUrlGameSessions                  string = RouteUrlBase + "/user/gamesessions"
	RouteUrlGetStudents                   string = RouteUrlBase + "/getStudents"
	RouteUrlGetUserInfo                   string = RouteUrlBase + "/getUserInfo/:id"
	RouteUrlUpdateVertical                string = RouteUrlBase + "/updateVertical"
	RouteUrlClasses                       string = RouteUrlBase + "/classes"
	RouteUrlRegisterTeacher               string = RouteUrlBase + "/register/teacher"
	RouteUrlRegisterStudent               string = RouteUrlBase + "/register/student"
	RouteUrlCheckUsername                 string = RouteUrlBase + "/register/checkUsername/:username"
	RouteUrlGetTeacherInfoForRegisterPage string = RouteUrlBase + "/teacher/get/:id"
	RouteUrlGetTeacherData                string = RouteUrlBase + "/teacher/get"
	RouteUrlUpdateStudentClass            string = RouteUrlBase + "/updateStudent/class"
	RouteUrlAddAssignment                 string = RouteUrlBase + "/assignments/add"
	RouteUrlGetAssignmentsTeacher         string = RouteUrlBase + "/assignments/get/teacher"
	RouteUrlStudent                       string = RouteUrlBase + "/teacher/student/:id"
	RouteUrlGetPasswordResetCode          string = RouteUrlBase + "/password/reset/:id"
	RouteUrlCheckPasswordResetCode        string = RouteUrlBase + "/password/check"
	RouteUrlUpdatePassword                string = RouteUrlBase + "/password/update"
)
