DROP SCHEMA IF EXISTS assignments CASCADE;
DROP SCHEMA IF EXISTS teachers CASCADE;
DROP SCHEMA IF EXISTS students CASCADE;
DROP SCHEMA IF EXISTS game_sessions CASCADE;
DROP SCHEMA IF EXISTS users CASCADE;
